#!/usr/bin/env python

from typing import Any, Callable
from argparse import ArgumentParser

from common import Log, KeyDefaultDict, ast_to_tree_string, hexdump


def main():
    parser = ArgumentParser(prog="syn", description="synthesize pl programs")
    parser.add_argument("source")
    parser.add_argument(
        "target",
        help="mp0, "
        "xbnf, xbnf-raw-ast, xbnf-ast, xbnf-formatted, "
        "a, a-raw-ast, a-ast, a-formatted, "
        "b, b-raw-ast, b-ast, b-formatted, "
        "b2, b2-raw-ast, b2-ast, b2-formatted, "
        "expr, expr-raw-ast, expr-ast, expr-formatted, "
        "regex, or regex-ast",
    )
    parser.add_argument(
        "-s",
        "--source-lang",
        type=str,
        default=None,
        help="xbnf, a, b, b2, expr, or regex",
    )
    parser.add_argument(
        "-w",
        "--waypoints",
        nargs="*",
        type=str,
        default=[],
        help="force intermediates in synthesis path",
    )
    parser.add_argument("-o", "--output-file", type=str, default=None)
    parser.add_argument(
        "-l",
        "--log-level",
        type=str,
        default="e",
        help="[n]one, [w]arn, [d]ebug, [e]rror, or [t]race",
    )
    args = parser.parse_args()

    Log.at(args.log_level)

    from synthesis import Source, synthesize

    str_artifact: KeyDefaultDict[str, Callable[[Any], str]] = KeyDefaultDict(
        lambda key: ast_to_tree_string if key.endswith("ast") else str,
        {"mp0": hexdump},
    )

    artifact: Any = synthesize(
        args.target, Source.load(args.source), args.source_lang, args.waypoints
    )

    if not args.output_file:
        print(str_artifact[args.target](artifact))

    else:
        with open(args.output_file, "w+") as f:
            f.write(str_artifact[args.target](artifact))


if __name__ == "__main__":
    main()
